// playground/vue/src/views/pagination.vue
<template>
  <span>{{ select.state.count }}</span>
  <el-button :type="select.state.isReq ? 'primary' : 'success'" @click="select.toggleRequest">changeRequest</el-button>
  <el-button :disabled="select.state.isSelectAll" @click="select.selectAll">all</el-button>
  <el-button :disabled="!select.state.isSelectAll" @click="select.selectCancel">cancel</el-button>
  <el-input v-model="query.a" style="height: 60px;" />
  <el-table
    :ref="select.ref"
    v-loading="data.loading"
    style="height: 100%"
    :data="data.list"
    @selection-change="select.selectChange"
  >
    <el-table-column type="selection" :selectable="() => !select.state.isSelectAll" />
    <el-table-column label="a" prop="a" />
    <el-table-column label="b" prop="b" />
  </el-table>
  <el-pagination
    layout="prev, pager, next"
    :total="data.total"
    :page-size="query.limit"
    :current-page="query.page"
    @size-change="page.limit"
    @current-change="page.page"
  />
</template>
<script lang="ts">
import { defineComponent, ref } from "vue"
import { usePaginationSelect, usePaginationTable } from "@poyoho/shared-vue"
import { request, RetType, Query } from "../../../mock/requestData"

export default defineComponent({
  setup() {
    const _req = ref(request)
    const { data, query, page, req } = usePaginationTable<Query, RetType>(_req, {})
    const select = usePaginationSelect(data, query, "a", _req)

    req()

    return {
      data,
      query,
      page,

      select,
    }
  },
})
</script>

// playground/react/src/views/pagination/index.tsx
import React, { useRef } from "react"
import { usePaginationTable, usePaginationSelect } from "@poyoho/shared-react"
import { Table, Input, Button } from "antd"
import { request, columns } from "../../../../mock/requestData"

interface Query {
  page: number
  limit: number
  a?: string
}

interface RetType {
  a: number
  b: number
}

const Pagination: React.FC = () => {
  let _req = useRef(request)
  const { data, query, setQuery, page, req } = usePaginationTable<Query, RetType>(_req)
  const selection = usePaginationSelect(data, query, "a", _req)

  return (
    <div>
      <span>{selection.state.count}</span>
      <Button
        type={selection.state.isReq ? 'primary' : 'default'}
        onClick={selection.toggleRequest}
      >changeRequest</Button>
      <Button disabled={selection.state.isSelectAll} onClick={selection.selectAll}>all</Button>
      <Button disabled={!selection.state.isSelectAll} onClick={selection.selectCancel}>cancel</Button>
      <Input placeholder="Basic usage"
        onPressEnter={(v) => {
          setQuery((prev) => ({ ...prev, a: v.currentTarget.value }))
        }}
      />
      <hr/>
      <Table
        rowKey="a"
        rowSelection={selection.rowSelection}
        columns={columns}
        dataSource={data.list}
        loading={data.loading}
        pagination={{
          total: data.total,
          current: query.page,
          pageSize: query.limit,
          onChange: page.page,
          onShowSizeChange: page.limit,
        }}
      />
    </div>
  );
};

export default Pagination
