// playground/vue/src/views/pagination.vue
<template>
  <span>{{ selectState.selectCount }}</span>
  <el-button v-if="state.useLocal" type="primary" @click="() => toggleFetchData()">查看所有</el-button>
  <el-button v-else type="success" @click="() => toggleFetchData()">查看选中</el-button>

  <el-button class="pagination-select-btn" @click="togglePageSelect" :disabled="selectState.selectAll" v-if="selectState.pageSelectCount < selectState.list.length || selectState.selectAll">
    本页全选
  </el-button>
  <el-button type="primary" @click="togglePageSelect" v-else>
    本页反选
  </el-button>

  <el-button :disabled="selectState.selectAll" @click="selectAll">全选</el-button>
  <el-button :disabled="!selectState.selectCount" @click="selectCancel">取消</el-button>
  <el-input v-model="query.a" style="height: 60px;" @change="toggleFetchData(false)"/>
  <el-table
    ref="tableRef"
    style="height: 100%"
    v-loading="state.loading"
    :data="selectState.list"
    @selection-change="selectChange"
    @select="selectChange"
  >
    <el-table-column type="selection" :selectable="() => !selectState.selectAll" />
    <el-table-column label="a" prop="a" />
    <el-table-column label="b" prop="b" />
  </el-table>
  <el-pagination
    layout="prev, pager, next"
    :total="selectState.total"
    :page-size="query.limit"
    :current-page="query.page"
    @size-change="getListForPageSizeChanged"
    @current-change="getListByPage"
  />
  <hr>
</template>
<script lang="ts">
import { defineComponent, reactive, ref, nextTick } from "vue"
import { request, RetType, Query } from "../../../mock/requestData"
import { usePaginationSelect, PaginationSelectState, SelectableRow } from "@poyoho/shared-service/pagination-select"


export default defineComponent({
  setup() {
    const tableRef = ref()

    const selectState = ref<PaginationSelectState<SelectableRow<RetType>>>({
      selectCount: 0,
      pageSelectCount: 0,
      total: 0,
      list: [] as SelectableRow<RetType>[],
      selectAll: false,
    })

    const query = reactive<Query>({
      page: 1,
      limit: 10,
    })

    const state = reactive({
      loading: false,
      useLocal: false,
    })

    const selectService = usePaginationSelect<Query, RetType>(
      () => "a",
      (query: Query) => request(query),
      () => ({ list: "list", total: "total"})
    )

    selectService.event.subscribe(state => {
      selectState.value = state
      nextTick(() => {
        selectState.value.list.forEach(row => tableRef.value?.toggleRowSelection(row, row.$selected))
      })
    })

    async function getList(useLocal: boolean) {
      state.loading = true
      await selectService.refresh(query, useLocal)
      state.loading = false
    }
    getList(state.useLocal)

    return {
      state,
      query,
      tableRef,
      selectState,

      async toggleFetchData(useLocal?: boolean) {
        let tmp;
        if (typeof useLocal === 'undefined') {
          tmp = !state.useLocal
        } else {
          tmp = useLocal
        }
        query.page = 1
        await getList(tmp)
        state.useLocal = tmp
      },
      getListByPage (page: number) {
        query.page = page
        getList(state.useLocal)
      },
      getListForPageSizeChanged (size: number) {
        query.page = 1
        query.limit = size
        getList(state.useLocal)
      },
      selectChange (rows: RetType[], currentRow: RetType) {
        selectService.SelectMergeRow(rows, currentRow)
      },
      selectAll () {
        selectService.selectAll()
        if (state.useLocal) {
          state.useLocal = false
          getList(state.useLocal)
        }
      },
      selectCancel () {
        selectService.selectCancel()
        if (state.useLocal) {
          state.useLocal = false
          getList(state.useLocal)
        }
      },
      togglePageSelect () {
        selectService.togglePageSelect()
      }
    }
  },
})
</script>

// playground/react/src/views/pagination/pagination.tsx
import React, { useRef, useState, useMemo } from "react"
import { Table, Input, Button } from "antd"
import { request, RetType, Query, columns } from "../../../../mock/requestData"
import { usePaginationSelect, PaginationSelectState, SelectableRow } from "@poyoho/shared-service"

const Pagination: React.FC = () => {
  const selectService = useRef(usePaginationSelect<Query, RetType>(
    () => "a",
    (query: Query) => request(query),
    () => ({ list: "list", total: "total"})
  ))
  const [selectState, setSelectState] = useState<PaginationSelectState<SelectableRow<RetType>>>({
    selectCount: 0,
    pageSelectCount: 0,
    total: 0,
    list: [] as SelectableRow<RetType>[],
    selectAll: false,
  })

  selectService.current.event.subscribe(state => {
    console.log('state change', state);
    setSelectState(state)
  })

  const [state, setState] = useState({
    loading: false,
    useLocal: false,
  })

  const [query, setQuery] = useState<Query>({
    page: 1,
    limit: 10,
  })

  useMemo(() => {
    getList(state.useLocal)
  }, [query])

  async function getList(useLocal: boolean) {
    setState({...state, loading: true})
    await selectService.current.refresh(query, useLocal)
    setState({...state, loading: false})
  }

  async function toggleFetchData(useLocal?: boolean) {
    let tmp: boolean;
    if (typeof useLocal === 'undefined') {
      tmp = !state.useLocal
    } else {
      tmp = useLocal
    }
    setState({...state, loading: false, useLocal: tmp})
    setQuery({ ...query, page: 1})
  }

  function pageChange (page: number) {
    setQuery({ ...query, page})
  }

  function limitChange (size: number) {
    setQuery({ ...query, page: 1, limit: size})
  }

  function selectAll () {
    selectService.current.selectAll()
    if (state.useLocal) {
      setState({...state, useLocal: false})
      setQuery({ ...query })
    }
  }

  function selectCancel () {
    selectService.current.selectCancel()
    if (state.useLocal) {
      setState({...state, useLocal: false})
      setQuery({ ...query })
    }
  }

  return (
    <div>
      <span>{selectState.selectCount}</span>
      {
        state.useLocal
        ? <Button type="primary" onClick={() => toggleFetchData()}>查看所有</Button>
        : <Button type="default" onClick={() => toggleFetchData()}>查看选中</Button>
      }

      {
        ((selectState.pageSelectCount < selectState.list.length) || selectState.selectAll)
        ? <Button type="primary" onClick={() => selectService.current.togglePageSelect()}>全选本页</Button>
        : <Button type="default" onClick={() => selectService.current.togglePageSelect()}>反选本页</Button>
      }

      <Button disabled={selectState.selectAll} onClick={selectAll}>全选</Button>
      <Button disabled={!selectState.selectAll} onClick={selectCancel}>取消</Button>
      <Input placeholder="Basic usage" onPressEnter={(v) => setQuery((prev) => ({ ...prev, a: v.currentTarget.value }))} />
      <hr/>
      <Table
        rowKey="a"
        columns={columns}
        dataSource={selectState.list}
        loading={state.loading}
        rowSelection={{
          type: "checkbox",
          getCheckboxProps: () => ({ disabled: selectState.selectAll }),
          selectedRowKeys: selectState.list.filter(el => el.$selected).map(el => el.a),
          onSelect: (record, _, selectedRows) => {
            selectService.current.SelectMergeRow(selectedRows, record)
          },
          onSelectAll(_, rows) {
            selectService.current.SelectMergeRow(rows)
          }
        }}
        pagination={{
          total: selectState.total,
          current: query.page,
          pageSize: query.limit,
          onChange: pageChange,
          onShowSizeChange: limitChange,
        }}
      />
    </div>
  );
};

export default Pagination
